### ISSUE TITLE
Lage menyer for multiplayer

### ISSUE THREAD

**Issue by selfjell** [inf112-v20/factoryRobots#107]
- [x] Prompt som spør om du vil være host eller joine server
- [x] Server setup screen
- [x] Join server prompt (enkel input boks hvor du kan legge inn ip)
- [x] Server lobby

**Comment by hally0** [comment]
Mangler litt lan funksjonalitet før vi kan lukke denne. GUI er for det meste ferdig når #114 blir merget.
