### ISSUE TITLE
Can't run the project 

### ISSUE THREAD

**Issue by CGRU2001** [inf112-v20/factoryRobots#117]
When I try to run the project, it throws an java.lang.ExceptionInInitializerError exception
![Screen Shot 2020-04-26 at 12 53 38](https://user-images.githubusercontent.com/58574687/80305444-fdcea080-87bc-11ea-9e6c-45301fd89607.png)

**Comment by selfjell** [comment]
Should work to run it with the VM argument -XstartOnFirstThread

**Comment by CGRU2001** [comment]
Not working with that argument

**Comment by selfjell** [comment]
What OS and java version are you running?

**Comment by CGRU2001** [comment]
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode) 

On Mac OS X El Capitan

**Comment by selfjell** [comment]
Don't have a solution for you right now as this is a work in progress. You could try updating your OS. It is working with the argument on java 8 in OS X Catalina.
