### ISSUE TITLE
Roboter stopper lasere: 

### ISSUE THREAD

**Issue by RagnhildKSteinsland** [inf112-v20/factoryRobots#37]
**Brukerhistorie**:
Som spiller ønsker jeg at laseren stopper på den første roboten den treffer, slik at jeg kan gjemme meg bak andre roboter, for å unngå å ta skade fra laser.

**Akseptansekrav**:
- Laserstråle stopper på første robot den treffer.
- Bare denne første roboten tar skade

**Arbeidsoppgaver**:
- [x] Bestemme stien laseren skal følge og sørge for at denne stopper når den skal.
- [x] Finne ut om det er en robot i enden av laserstrålen.
- [x] Dersom det er en robot i enden, gi denne roboten skade.
- [x] Tegne laserstrålens sti grafisk.

**Comment by selfjell** [comment]
fixed in #90

**Comment by selfjell** [comment]
**Brukerhistorie**: 
Som spiller ønsker jeg å at jeg skal kunne gjemme meg bak andre roboter, for å unngå å ta skade fra laser. 

**Akseptansekrav**: 
- Laserstråle stopper på første robot den treffer.
- Bare denne første roboten tar skade

**Arbeidsoppgaver**:
- Bestemme stien laseren skal følge og sørge for at denne stopper når den skal.
- Finne ut om det er en robot i enden av laserstrålen.
- Dersom det er en robot i enden, gi denne roboten skade.
- Tegne laserstrålens sti grafisk.
