### ISSUE TITLE
Implementere runder

### ISSUE THREAD

**Issue by hally0** [inf112-v20/factoryRobots#40]
Brukerhistorie:
Spiller ønsker å spille rundebasert Robo Rally for å lage strategi og planlegge bevegelser.

Akseptansekrav:
Rundene må følge runde strukturen til Robo Rally.

Arbeidsoppgaver:
- Hver fase skal gå i rett rekkefølge
- Initiering av hver fase og runde skal ferdigstilles riktig måte
- Implementere powerdown
- Få powerdown til å tre i kraft på riktig tidspunkt i runden
- At utdeling og programmering av kort blir gjort riktig

**Comment by selfjell** [comment]
- Lasere må trigges
- Objekter må manipulere roboter
- De som har låste cardslots må ikke få fjernet de låste kortene
- Siste fase så må powerdown resettes
- Sjekke om spiller er i powerdown i doPhase
