### ISSUE TITLE
Implementer musikk og lydeffekter

### ISSUE THREAD

**Issue by selfjell** [inf112-v20/factoryRobots#73]
- [x] Meny musikk
- [x] Lydeffekter på knapper
- [x] Lydeffekter på spillet
- [x] Spill musikk

**Comment by hally0** [comment]
https://github.com/libgdx/libgdx/wiki/Sound-effects

https://www.codeproject.com/Questions/1191177/How-to-play-sound-in-gdx

Jeg tror du må legge til bakgrunnsmusikken i RoboRally. Usikker på hvor du bør implementere lydeffekter.

Helst brukt asset manager: https://github.com/libgdx/libgdx/wiki/Managing-your-assets
